version: "3.8"

services:
  jenkins:
    build: .
    container_name: my_marvin_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/my_marvin.yml

      - USER_CHOCOLATEEN_PASSWORD=motdepasse1
      - USER_VAUGIE_G_PASSWORD=motdepasse2
      - USER_I_DONT_KNOW_PASSWORD=motdepasse3
      - USER_NASSO_PASSWORD=motdepasse4

    volumes:
      - jenkins_home:/var/jenkins_home
      - ./my_marvin.yml:/var/jenkins_home/casc_configs/my_marvin.yml:ro
      - ./job_dsl.groovy:/var/jenkins_home/job_dsl.groovy:ro
    restart: unless-stopped

volumes:
  jenkins_home:
