version: "3.8"

services:
  jenkins:
    build: .
    container_name: my_marvin_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/my_marvin.yml

      - USER_CHOCOLATEEN_PASSWORD=${USER_CHOCOLATEEN_PASSWORD}
      - USER_VAUGIE_G_PASSWORD=${USER_VAUGIE_G_PASSWORD}
      - USER_I_DONT_KNOW_PASSWORD=${USER_I_DONT_KNOW_PASSWORD}
      - USER_NASSO_PASSWORD=${USER_NASSO_PASSWORD}


    volumes:
      - jenkins_home:/var/jenkins_home
      - ./my_marvin.yml:/var/jenkins_home/casc_configs/my_marvin.yml:ro
      - ./job_dsl.groovy:/var/jenkins_home/workspace/Tools/SEED/job_dsl.groovy
    restart: unless-stopped

volumes:
  jenkins_home:
