def githubName = binding.variables['GITHUB_NAME']
def displayName = binding.variables['DISPLAY_NAME']

if (!githubName || !displayName) {
    throw new IllegalArgumentException("GITHUB_NAME and DISPLAY_NAME parameters must be set")
}


// Dossier Tools
      folder('Tools') {
        description('Folder for miscellaneous tools.')
      }

      // Job Tools/clone-repository
      freeStyleJob('Tools/clone-repository') {
        description('Job to clone a Git repository')

        parameters {
          stringParam('GIT_REPOSITORY_URL', '', 'Git URL of the repository to clone')
        }

        wrappers {
          preBuildCleanup()
        }

        steps {
          shell('git clone "$GIT_REPOSITORY_URL"')
        }
      }

      // Job Tools/SEED
      freeStyleJob('Tools/SEED') {
        description('Job to create dynamic jobs from Job DSL')

        parameters {
          stringParam('GITHUB_NAME', '', '"GitHub repository owner/repo_name" description (e.g.: "EpitechIT31000/chocolatine")')
          stringParam('DISPLAY_NAME', '', 'Display name for the job')
        }

        steps {
            dsl {
            text('''

            freeStyleJob(displayName) {
    description("Job generated by SEED for GitHub repository: ${githubName}")

    properties {
        githubProjectUrl("https://github.com/${githubName}")
    }

    scm {
        git {
            remote {
                url("https://github.com/${githubName}.git")
            }
            branches('*/main', '*/master')
        }
    }

    triggers {
        scm('* * * * *')
    }

    wrappers {
        preBuildCleanup()
    }

    steps {
        shell('make fclean')
        shell('make')
        shell('make tests_run')
        shell('make clean')
    }


}
            
            ''')
  }
}

      }

