//Folder Tools
folder('Tools') {
  description('Folder for miscellaneous tools.')
}

freeStyleJob('Tools/clone-repository') {
  description('Job to clone a Git repository')

  parameters {
    stringParam('GIT_REPOSITORY_URL', '', 'Git URL of the repository to clone')
  }

  wrappers {
    preBuildCleanup()
  }

  steps {
    shell('git clone "$GIT_REPOSITORY_URL"')
  }
}

// === Job Tools/SEED 
freeStyleJob('Tools/SEED') {
  description('Job to create dynamic jobs from Job DSL')

 parameters {
  stringParam(
    'GITHUB_NAME',
    '',
    'GitHub repository owner/repo_name (e.g.: "EpitechIT31000/chocolatine")'
  )
  stringParam(
    'DISPLAY_NAME',
    '',
    'Display name for the job'
  )
}

  steps {
    dsl {
      text('''
  freeStyleJob("${DISPLAY_NAME}") {
  description("Job generated by SEED for GitHub repository: ${GITHUB_NAME}")

  properties {
    githubProjectUrl("https://github.com/${GITHUB_NAME}")
  }

  scm {
    git {
      remote {
        url("https://github.com/${GITHUB_NAME}.git")
      }
      branches('*/main', '*/master')
    }
  }

  triggers {
    scm('* * * * *')
  }

  wrappers {
    preBuildCleanup()
  }

  steps {
    shell('make fclean')
    shell('make')
    shell('make tests_run')
    shell('make clean')
  }
}
''')

    }
  }
}
