def githubName = binding.variables['GITHUB_NAME']
def displayName = binding.variables['DISPLAY_NAME']

if (!githubName || !displayName) {
    throw new IllegalArgumentException("GITHUB_NAME and DISPLAY_NAME parameters must be set")
}

freeStyleJob(displayName) {
    description("Job generated by SEED for GitHub repository: ${githubName}")

    properties {
        githubProjectUrl("https://github.com/${githubName}")
    }

    scm {
        git {
            remote {
                url("https://github.com/${githubName}.git")
            }
            branches('*/main', '*/master')
        }
    }

    triggers {
        scm('* * * * *')
    }

    wrappers {
        preBuildCleanup()
    }

    steps {
        shell('make fclean')
        shell('make')
        shell('make tests_run')
        shell('make clean')
    }
}